// ==UserScript==
// @name         YouTube Age Restriction Bypass (Stealth Version)
// @namespace    http://tampermonkey.net/
// @version      5.0
// @author       
// @match        *://www.youtube.com/*
// @grant        none
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Advanced20YouTube20Age20Restriction20Bypass.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Advanced20YouTube20Age20Restriction20Bypass.meta.js
// ==/UserScript==
!function(){"use strict";function t(t){if(!t?.playabilityStatus)return t;const e=t.playabilityStatus.status;return["AGE_VERIFICATION_REQUIRED","LOGIN_REQUIRED","UNPLAYABLE","RESTRICTED"].includes(e)&&(t.playabilityStatus.status="OK",delete t.playabilityStatus.errorScreen,delete t.playabilityStatus.messages,n("Patched playability status.")),t}function e(){const t=document.createElement("script");t.textContent="\n      (function() {\n        try {\n          const patch = (res) => {\n            if (!res?.playabilityStatus) return;\n            const status = res.playabilityStatus.status;\n            if (['AGE_VERIFICATION_REQUIRED','RESTRICTED','LOGIN_REQUIRED'].includes(status)) {\n              res.playabilityStatus.status = 'OK';\n              delete res.playabilityStatus.errorScreen;\n              console.log('[YTBypass] ytInitialPlayerResponse patched.');\n            }\n          };\n          if (window.ytInitialPlayerResponse) patch(window.ytInitialPlayerResponse);\n          if (window.ytplayer?.config?.args?.player_response) {\n            const res = JSON.parse(window.ytplayer.config.args.player_response);\n            patch(res);\n            window.ytplayer.config.args.player_response = JSON.stringify(res);\n          }\n        } catch (_) {}\n      })();\n    ",document.documentElement.appendChild(t),t.remove()}const n=()=>!1,s=window.fetch;window.fetch=new Proxy(s,{apply:(e,n,s)=>Reflect.apply(e,n,s).then(async e=>{const n=e.clone();if(("string"==typeof s[0]?s[0]:s[0].url||"").includes("/youtubei/v1/player"))try{const s=await n.json(),a=t(JSON.parse(JSON.stringify(s))),r=new Blob([JSON.stringify(a)],{type:"application/json"});return new Response(r,{status:e.status,statusText:e.statusText,headers:e.headers})}catch(t){return t.message,e}return e})});const a=XMLHttpRequest;window.XMLHttpRequest=new Proxy(a,{construct(e,n){const s=new e(...n);let a=!1;const r=s.open;s.open=function(t,e){return a=e.includes("/youtubei/v1/player"),r.apply(this,arguments)};const i=s.send;return s.send=function(){return a&&s.addEventListener("readystatechange",function(){if(4===s.readyState&&""===s.responseType&&s.responseText)try{t(JSON.parse(s.responseText))}catch(t){}}),i.apply(this,arguments)},s}}),new MutationObserver(()=>{document.querySelector("ytd-watch-flexy[is-restricted]")&&setTimeout(e,1e3)}).observe(document.body,{childList:!0,subtree:!0})}();