// ==UserScript==
// @name         Better Google
// @namespace    google
// @version      0.1.16.10
// @author       aligo, adambh, tejaslodaya, drwonky, yut23
// @license      MIT
// @homepageURL   https://github.com/aligo/better-google
// @match        https://*.google.com/search?*
// @include      /^https?://(?:www|encrypted|ipv[46])\.google\.[^/]+/(?:$|[#?]|search|webhp)/
// @grant        none
// @run-at       document-start
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Better20Google.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Better20Google.meta.js
// ==/UserScript==
!function(){"use strict";var e=function(e){var t,n,r,l,i,o,c,d,a,u,s,h,m=e.querySelectorAll(".TbwUpd, .HGLrXd");if(m.length>0){t=[".yuRUbf > a",".yuRUbf > div > a",".yuRUbf > div > span > a"];for(const r of t)if(n=e.querySelector(r))break;if((r=n.nextSibling)||(r=n.parentElement.nextSibling),!r)return;for((l=document.createElement("div")).className="btrAdd",i=0;i<r.children.length;i++)(o=r.children[i]).className.includes("TbwUpd")||o.className.includes("HGLrXd")||l.appendChild(o);(c=document.createElement("div")).className="btrG",c.appendChild(l),e.appendChild(c),(d=document.createElement("a")).href=n.href,d.target="_blank",d.className="btrLink",(a=document.createElement("cite")).innerText=n.href,a.className="iUh30 bc",d.appendChild(a),u=e.clientWidth-l.offsetWidth-10,c.insertBefore(d,l),d.offsetWidth>u&&(d.style.width=u.toString()+"px"),(s=e.querySelectorAll(".csDOgf")).length>0&&c.appendChild(s[0]),m.forEach(function(e){e.remove()}),(h=n.querySelector("br:first-child"))&&h.remove()}},t=0,n=!1,r=function(){var l;t!=document.querySelectorAll(".MjjYud .yuRUbf").length&&(document.querySelectorAll(".MjjYud .yuRUbf").forEach(e),t=document.querySelectorAll(".MjjYud .yuRUbf").length),n||(null!=MutationObserver&&(l=document.getElementById("rcnt"),new MutationObserver(r).observe(l,{childList:!0,subtree:!0})),n=!0)},l=function(e,t){null==document.querySelector(e)?null!=window.requestAnimationFrame?window.requestAnimationFrame(function(){l(e,t)}):document.addEventListener("readystatechange",function(){"complete"==document.readyState&&t()}):t()};l("head",function(){var e,t="#006621",n=document.querySelector('meta[name="color-scheme"]');null!=n&&n.content.includes("dark")&&(t="#40965b"),(e=document.createElement("style")).setAttribute("media","screen"),e.appendChild(document.createTextNode("")),document.head.appendChild(e),e.sheet.insertRule(`:root { --btrG-link-color: ${t}; }`),e.sheet.insertRule(".btrG { word-break: normal; line-height: 18px; }"),e.sheet.insertRule(".btrG .btrAdd { display: inline-block; vertical-align: top; line-height: 0; }"),e.sheet.insertRule(".btrG .btrLink { display: inline-block; vertical-align: top; line-height: 18px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; text-decoration: none !important; color: var(--btrG-link-color); }"),e.sheet.insertRule(".btrG .btrLink cite.iUh30 { color: var(--btrG-link-color); font-size: 16px; }"),e.sheet.insertRule(".yuRUbf h3.DKV0Md { margin-top: 0px; }")}),l("#rcnt",r)}();