// ==UserScript==
// @name         Better Google
// @namespace    google
// @version      0.1.16.11
// @author       aligo, adambh, tejaslodaya, drwonky, yut23
// @license      MIT
// @homepageURL   https://github.com/aligo/better-google
// @match        https://*.google.com/search?*
// @include      /^https?://(?:www|encrypted|ipv[46])\.google\.[^/]+/(?:$|[#?]|search|webhp)/
// @grant        none
// @run-at       document-start
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Better20Google.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Better20Google.meta.js
// ==/UserScript==
!function(){"use strict";var e=function(e){var t,n,r,i,l,d,o,a,c,s,u,h,m=e.querySelectorAll(".TbwUpd, .HGLrXd");if(m.length>0){t=[".yuRUbf > a",".yuRUbf > div > a",".yuRUbf > div > span > a"];for(const r of t)if(n=e.querySelector(r))break;if((r=n.nextSibling)||(r=n.parentElement.nextSibling),!r)return;for((i=document.createElement("div")).className="btrAdd",l=0;l<r.children.length;l++)(d=r.children[l]).className.includes("TbwUpd")||d.className.includes("HGLrXd")||i.appendChild(d);(o=document.createElement("div")).className="btrG",o.appendChild(i),e.appendChild(o),(a=document.createElement("a")).href=n.href,a.target="_blank",a.className="btrLink",(c=document.createElement("cite")).innerText=n.href,c.className="iUh30 bc",a.appendChild(c),s=e.clientWidth-i.offsetWidth-10,o.insertBefore(a,i),a.offsetWidth>s&&(a.style.width=s.toString()+"px"),(u=e.querySelector(".csDOgf"))&&u.parentElement!==i&&i.appendChild(u),m.forEach(function(e){e.remove()}),(h=n.querySelector("br:first-child"))&&h.remove()}},t=0,n=!1,r=function(){var i;t!=document.querySelectorAll(".MjjYud .yuRUbf").length&&(document.querySelectorAll(".MjjYud .yuRUbf").forEach(e),t=document.querySelectorAll(".MjjYud .yuRUbf").length),n||(null!=MutationObserver&&(i=document.getElementById("rcnt"),new MutationObserver(r).observe(i,{childList:!0,subtree:!0})),n=!0)},i=function(e,t){null==document.querySelector(e)?null!=window.requestAnimationFrame?window.requestAnimationFrame(function(){i(e,t)}):document.addEventListener("readystatechange",function(){"complete"==document.readyState&&t()}):t()};i("head",function(){var e,t="#006621",n=document.querySelector('meta[name="color-scheme"]');null!=n&&n.content.includes("dark")&&(t="#40965b"),(e=document.createElement("style")).setAttribute("media","screen"),e.appendChild(document.createTextNode("")),document.head.appendChild(e),e.sheet.insertRule(`:root { --btrG-link-color: ${t}; }`),e.sheet.insertRule(".btrG { display: flex; align-items: center; gap: 6px; word-break: normal; line-height: 18px; }"),e.sheet.insertRule(".btrG .btrAdd { display: inline-flex; align-items: center; flex: 0 0 auto; line-height: 18px; }"),e.sheet.insertRule(".btrG .btrAdd .csDOgf { display: inline-flex; align-items: center; height: 18px; margin: 0; padding: 0; }"),e.sheet.insertRule('.btrG .btrAdd .csDOgf > div, .btrG .btrAdd .csDOgf [role="button"] { display: inline-flex; align-items: center; height: 18px; margin: 0; padding: 0; }'),e.sheet.insertRule(".btrG .btrLink { display: block; flex: 0 1 auto; min-width: 0; line-height: 18px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; text-decoration: none !important; color: var(--btrG-link-color); }"),e.sheet.insertRule(".btrG .btrLink cite.iUh30 { color: var(--btrG-link-color); font-size: 16px; }"),e.sheet.insertRule(".yuRUbf h3.DKV0Md { margin-top: 0px; }")}),i("#rcnt",r)}();