// ==UserScript==
// @name    🔥🔥🔥文本选中复制(通用)🔥🔥🔥
// @name:en Text Copy Universal
// @namespace  https://github.com/WindrunnerMax/TKScript
// @version    1.1.3
// @author     Czy
// @match      http://*/*
// @match      https://*/*
// @supportURL https://github.com/WindrunnerMax/TKScript/issues
// @license    GPL License
// @run-at     document-end
// @grant      GM_registerMenuCommand
// @grant      GM_unregisterMenuCommand
// @grant      GM_notification
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/F09F94A5F09F94A5F09F94A5E69687E69CACE98089E4B8ADE5A48DE588B628E9809AE794A829F09F94A5F09F94A5F09F94A5.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/F09F94A5F09F94A5F09F94A5E69687E69CACE98089E4B8ADE5A48DE588B628E9809AE794A829F09F94A5F09F94A5F09F94A5.meta.js
// ==/UserScript==
!function(){"use strict";var e,t,n,o,c,r;t='.__copy-currency-container{background-color:#4c98f7;border-radius:3px;bottom:0;display:flex;flex-direction:column;left:-150px;position:fixed;transition:all .3s;width:150px;z-index:9999999999}.__copy-currency-container:before{background-color:#4c98f7;border-radius:20px;content:"";cursor:pointer;height:20px;position:absolute;right:-6px;top:calc(50% - 10px);width:20px}.__copy-currency-container:hover{left:0}.__copy-currency-container>.__copy-currency-button{border:1px solid #fff;border-radius:3px;color:#fff!important;cursor:pointer;font-size:12px!important;margin:5px;padding:5px 3px 5px 4px;text-align:center;user-select:none;z-index:9999999999}',void 0===n&&(n={}),o=n.insertAt,t&&"undefined"!=typeof document&&(c=document.head||document.getElementsByTagName("head")[0],(r=document.createElement("style")).type="text/css","top"===o&&c.firstChild?c.insertBefore(r,c.firstChild):c.appendChild(r),r.styleSheet?r.styleSheet.cssText=t:r.appendChild(document.createTextNode(t)));const s="true",a="copy-currency--",d=e=>e.stopPropagation();(e=>{const t=document.createElement("div");t.className="__copy-currency-container",document.body.appendChild(t),e.forEach(e=>{const n=document.createElement("div");n.className="__copy-currency-button";const o=localStorage.getItem(a+e.storageKey);e.status=o===s?1:0;const c=()=>{1===e.status?(e.openFunction(),e.status=0,n.textContent=e.closeName,localStorage.setItem(a+e.storageKey,s)):(e.closeFunction(),e.status=1,n.textContent=e.openName,localStorage.setItem(a+e.storageKey,"false"))};c(),n.addEventListener("click",c),t.appendChild(n)})})([{status:(e=(e=>(e[e.OPEN=0]="OPEN",e[e.CLOSE=1]="CLOSE",e))(e||{})).CLOSE,storageKey:"selectstart-and-copy",openName:"✅ 启动解除复制限制",closeName:"❌ 关闭解除复制限制",openFunction:()=>{window.addEventListener("selectstart",d,!0),window.addEventListener("copy",d,!0),(e=>{const t=document.createElement("style");t.id=e,t.innerText="*{user-select: auto !important;-webkit-user-select: auto !important;}";const[n]=document.getElementsByTagName("body");n?n.appendChild(t):window.addEventListener("DOMContentLoaded",()=>document.body.appendChild(t))})(a+"selectstart-and-copy")},closeFunction:()=>{window.removeEventListener("selectstart",d,!0),window.removeEventListener("copy",d,!0),(e=>{const t=document.getElementById(e);t&&t.remove()})(a+"selectstart-and-copy")}},{status:e.CLOSE,storageKey:"contextmenu",openName:"✅ 启动解除右键限制",closeName:"❌ 关闭解除右键限制",openFunction:()=>window.addEventListener("contextmenu",d,!0),closeFunction:()=>window.removeEventListener("contextmenu",d,!0)},{status:e.CLOSE,storageKey:"keydown",openName:"✅ 启动解除键盘限制",closeName:"❌ 关闭解除键盘限制",openFunction:()=>window.addEventListener("keydown",d,!0),closeFunction:()=>window.removeEventListener("keydown",d,!0)}])}();