// ==UserScript==
// @name     Microsoft Store Direct Download
// @namespace    StephenP
// @version  2.0.4
// @author       StephenP
// @grant    GM.xmlHttpRequest
// @connect	 rg-adguard.net
// @match    https://apps.microsoft.com/*
// @match    https://apps.microsoft.com/*
// @contributionURL https://buymeacoffee.com/stephenp_greasyfork
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Microsoft20Store20Direct20Download.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Microsoft20Store20Direct20Download.meta.js
// ==/UserScript==
function e(l,o){try{n.firstChild.innerText="...";var d="type="+o+"&url="+l+"&ring=RP&lang=it-IT";GM.xmlHttpRequest({method:"POST",url:"https://store.rg-adguard.net/api/GetFiles",data:d,headers:{"Content-Type":"application/x-www-form-urlencoded"},onload:function(l){var d,i;n.firstChild.innerText="▼";try{(d=r("#linkTable"))[0].parentNode.removeChild(d[0]),(i=r("#messageFromServer"))[0].parentNode.removeChild(i[0])}catch(e){console.log(e)}try{t(l,o)}catch(n){console.log(n),"ProductId"===o?t(n,o):e(r("[product-id]")[0].getAttribute("product-id"),"ProductId")}}})}catch(n){console.log(n),"ProductId"===o?t(n,o):e(r("[product-id]")[0].getAttribute("product-id"),"ProductId")}}function t(t,l){var o,d,i=document.createElement("div");if(i.innerHTML=t.responseText,o=i.getElementsByTagName("TABLE")[0],(d=i.getElementsByTagName("P")[0]).id="messageFromServer",d.style.fontWeight="bold",void 0!==o){if(!document.getElementById("realign")){let e=document.createElement("STYLE");e.id="realign",e.innerText="div.details.two-column{display: initial}}",document.getElementsByTagName("HEAD")[0].appendChild(e)}o.id="linkTable";const e=o.getElementsByTagName("TBODY")[0].getElementsByTagName("TR");for(let t of e)t.firstChild.firstChild&&t.firstChild.firstChild.innerHTML.match(/\.appx$|\.appxbundle$|\.msix$|\.msixbundle$|\.exe$/)&&(t.style.fontWeight="bold");let t=document.createElement("STYLE");t.innerHTML="td:last-child{word-break: break-all}";let n=r("sl-card");if(n.length>0){const e=n[0].parentNode;e.insertBefore(o,e.querySelector("sl-card")),e.insertBefore(t,e.querySelector("sl-card")),o.style.marginTop="2em",d.style.color="green",e.insertBefore(d,e.querySelector("sl-card"))}}else void 0===o&&"url"===l?e(r("[product-id]")[0].getAttribute("product-id"),"ProductId"):(d.style.color="red",n.parentNode.parentNode.parentNode.appendChild(d))}function r(e,t=document.body){const n=Array.from(t.querySelectorAll("*")).map(e=>e.shadowRoot).filter(Boolean).map(t=>r(e,t));return Array.from(t.querySelectorAll(e)).concat(n).flat()}var n;setInterval(function(){let t=r(".buy-box-container");t.length>0&&0==r("#dlBtn").length&&((n=document.createElement("DIV")).id="dlBtn",n.setAttribute("aria-label","Download from AdGuard Store"),n.style.background="#00a686",n.style.font="initial",n.style.textAlign="center",n.style.borderRadius="var(--sl-input-border-radius-large)",n.style.marginTop="0.5em",n.innerText="",n.appendChild(document.createElement("P")),n.firstChild.innerText="▼",n.addEventListener("click",function(){e(document.location.href,"url")}),t[0].appendChild(n))},1e3);