// ==UserScript==
// @name         Telegram Web - Allow Saving Content
// @namespace    c0d3r
// @license      MIT
// @version      0.5
// @author       c0d3r
// @match        https://web.telegram.org/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=telegram.org
// @grant        unsafeWindow
// @grant        GM_addStyle
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Telegram20Web2020Allow20Saving20Content.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Telegram20Web2020Allow20Saving20Content.meta.js
// ==/UserScript==
function e(e){var t;e.media&&(t=e.media.document||e.media.photo),t&&unsafeWindow.appDownloadManager.downloadToDisc({media:t})}!function(){"use strict";var t,n,o,a,i,s;window.location.pathname.startsWith("/a/")?window.location.replace(window.location.href.replace(".org/a/",".org/k/")):(t=document.querySelector("#column-center"),n=["photo","audio","video","voice-message","media-round","grouped-item","document-container","sticker"],o=!1,GM_addStyle(".no-forwards .bubbles, .bubble, .bubble-content { -webkit-user-select: text!important; -moz-user-select: text!important; user-select: text!important; }"),s=EventTarget.prototype.addEventListener,EventTarget.prototype.addEventListener=function(e){"copy"!==e&&s.apply(this,arguments)},t.addEventListener("mouseup",function(e){if(2===e.button&&(o=!1,document.querySelector(".no-forwards"))){var t=e.target.closest("[data-mid]");t&&n.some(function(e){return t.classList.contains(e)})&&(a=t.dataset.mid,i=t.dataset.peerId,o=!0)}}),new MutationObserver(function(t){t.forEach(function(t){t.addedNodes.forEach(function(t){"bubble-contextmenu"===t.id&&o&&(t.querySelector(".btn-menu-item").insertAdjacentHTML("beforebegin",'<div class="btn-menu-item rp-overflow" id="down-btn"><span class="mytgico btn-menu-item-icon" style="font-size: 16px;">📥</span><span class="i18n btn-menu-item-text">Download</span></div>'),t.querySelector("#down-btn").addEventListener("click",function(){!async function(t,n){e(await unsafeWindow.mtprotoMessagePort.getMessageByPeer(t,n))}(i,a)})),t.classList&&t.classList.contains("selection-wrapper")&&(t.querySelector(".selection-container-left").insertAdjacentHTML("beforeend",'&nbsp;&nbsp;<button class="btn-primary btn-transparent text-bold" id="batch-btn" title="Download Media"><span class="mytgico" style="padding-bottom: 2px;">📥</span>&nbsp;<span class="i18n">D/L</span></button>'),t.querySelector("#batch-btn").addEventListener("click",function(){!async function(){var t=await unsafeWindow.appImManager.chat.selection.getSelectedMessages(),n=0,o=document.querySelector("#batch-btn"),a=o.querySelector(".i18n"),i=o.querySelector(".mytgico");t.forEach(function(s,c){s.media&&(s.media.document||s.media.photo)&&(function(t,n,o,a,i){setTimeout(function(){o.disabled=!0,o.style.opacity=.6,a.textContent=".."+(t+1)+"..",i.textContent="🕔",e(n)},1e3*t)}(n,s,o,a,i),n++),c===t.length-1&&setTimeout(function(){o.disabled=!1,o.style.opacity=1,a.textContent="D/L",i.textContent="📥"},1e3*n)})}()}))})})}).observe(t,{subtree:!0,childList:!0}))}();