// ==UserScript==
// @name         Telegram Web Media Downloader — Save Restricted Photos & Videos (Batch) + Copy Text
// @namespace    c0d3r
// @license      MIT
// @version      1.0
// @author       copyMister
// @match        https://web.telegram.org/*
// @match        https://webk.telegram.org/*
// @match        https://webz.telegram.org/*
// @icon         https://web.telegram.org/k/assets/img/favicon.ico
// @grant        none
// @run-at       document-start
// @downloadURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Telegram20Web2020Allow20Saving20Content.user.js
// @updateURL https://raw.githubusercontent.com/king1x32/compiledUserscripts/release/release/Telegram20Web2020Allow20Saving20Content.meta.js
// ==/UserScript==
!function(){"use strict";async function e(e){const t=c(e),n=a.appDownloadManager;n?t&&await n.downloadToDisc({media:t}):console.warn("[tg-save] appDownloadManager missing — WebK internals changed?")}function t(t){const n=t.querySelector(".btn-menu-item");if(!r||!n||t.querySelector("#nk-tg-down"))return;const{peerId:o,mid:a}=r;n.insertAdjacentHTML("beforebegin",'<div class="btn-menu-item rp-overflow" id="nk-tg-down"><span class="btn-menu-item-icon" style="font-size:1rem">📥</span><span class="btn-menu-item-text">Download</span></div>'),t.querySelector("#nk-tg-down").addEventListener("click",()=>e(d(o,a)).catch(e=>console.warn("[tg-save] download failed",e)))}function n(e){const t=e.querySelector(".selection-container");t&&!t.querySelector("#nk-tg-batch")&&(t.insertAdjacentHTML("beforeend",'<button id="nk-tg-batch" class="btn-primary btn-transparent text-bold" title="Download selected media" style="cursor:pointer;width:auto;"><span style="font-size:1rem;margin:0 .4rem .2rem 0;">📥</span> <span class="nk-txt">D/L</span></button>'),t.querySelector("#nk-tg-batch").addEventListener("click",o))}async function o(){const t=a.appImManager?.chat?.selection,n=document.querySelector("#nk-tg-batch .nk-txt"),o=(await(t?.getSelectedMessages())||[]).filter(c);if(!o.length)return n.textContent="N/A",await s(1500),void(n.textContent="D/L");const d=document.getElementById("nk-tg-batch");d.disabled=!0,d.style.opacity=.6;for(let t=0;t<o.length;t++){n.textContent=t+1+"/"+o.length;try{await e(o[t])}catch(e){console.warn("[tg-save] batch item failed",e)}t<o.length-1&&await s(1e3)}d.disabled=!1,d.style.opacity=1,n.textContent="D/L",t?.cancelSelection()}if("webk.telegram.org"!==location.hostname&&!location.pathname.startsWith("/k/"))return void location.replace("https://web.telegram.org/k/"+location.hash);const a="undefined"!=typeof unsafeWindow?unsafeWindow:window,s=e=>new Promise(t=>setTimeout(t,e)),c=e=>e&&e.media&&(e.media.document||e.media.photo),d=(e,t)=>a.mtprotoMessagePort?.getMessageByPeer(e,+t);let r=null;document.addEventListener("mouseup",e=>{if(r=null,2!==e.button)return;const t=e.target.closest("[data-mid]");t&&t.closest(".no-forwards")&&c(d(t.dataset.peerId,t.dataset.mid))&&(r={peerId:t.dataset.peerId,mid:t.dataset.mid})}),document.addEventListener("copy",e=>{const t=getSelection()?.anchorNode,n=t&&(1===t.nodeType?t:t.parentElement);n?.closest(".no-forwards")&&e.stopImmediatePropagation()},!0);const i=document.createElement("style");i.textContent=".bubble.no-forwards,.bubble.no-forwards *{-webkit-user-select:text!important;user-select:text!important}",(document.head||document.documentElement).appendChild(i);const l=new MutationObserver(e=>{for(const o of e)for(const e of o.addedNodes)1===e.nodeType&&("bubble-contextmenu"===e.id?t(e):e.classList.contains("selection-wrapper")&&n(e))}),m=()=>l.observe(document.body,{childList:!0,subtree:!0});document.body?m():document.addEventListener("DOMContentLoaded",m,{once:!0})}();